version: "3.9"

services:
  app:
    image: "${IMAGE_NAME}:latest"
    container_name: atos-application
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
